apiVersion: v1

kind: ConfigMap

metadata:

  name: wordpress-config

data:

  WORDPRESS_DATABASE_HOST: mariadb-service

  MARIADB_USER: hng_wordpress 

  MARIADB_DATABASE: hng11_wordpress

  MARIADB_VERSION: {{ .Values.mariadb_version }}

  MARIADB_LOCATION: {{ .Values.mariadb_location }}

---
apiVersion: v1

kind: Secret

metadata:

  name: wordpress-secrets

type: Opaque

data:
  MARIADB_PASSWORD: aG5nMTFfMjAyNA==
