apiVersion: apps/v1

kind: Deployment

metadata:

  name: mariadb-deployment

spec:

  replicas: 1

  selector:

    matchLabels:

      app: mariadb

  template:

    metadata:

      labels:

        app: mariadb

    spec:

      containers:

      - name: mariadb

        image: hngtech11/mariadb:day1

        # env:

        #   - name: MARIADB_USER

        #     value: hng_wordpress

        #   - name: MARIADB_PASSWORD

        #     value: hng11_2024

        #   - name: MARIADB_DATABASE

        #     value: hng11_wordpress
        env:
        # Define the environment variable
          - name: MARIADB_USER
            valueFrom: 
              secretKeyRef: 
                key: mariadb_user
                name: wordpress-db-creds

          - name: MARIADB_PASSWORD
            valueFrom: 
              secretKeyRef: 
                key: mariadb_password
                name: wordpress-db-creds

          - name: MARIADB_DATABASE
            valueFrom:
              configMapKeyRef:
                # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
                name: mariadb-wordpress-config
                # Specify the key associated with the value
                key: mariadb_database

---
apiVersion: v1

kind: Service

metadata:

  name: mariadb-service

spec:

  type: NodePort

  selector:

    app: mariadb

  ports:

    - protocol: TCP

      port: 3306

      targetPort: 3306
