apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fastapi-data-claim
  labels:
    app: fastapi
spec:
  accessModes:
   - ReadWriteOnce
  resources:
   requests:
    storage: 5Gi

---

apiVersion: apps/v1

kind: Deployment

metadata:

  name: api-deployment

spec:

  replicas: 1

  selector:

    matchLabels:

      app: api

  template:

    metadata:

      labels:

        app: api

    spec:

      containers:

      - name: api

        image: joseun/fastapi:day2

        env:

          - name: HNG_LESSON_DAY

            valueFrom:

              configMapKeyRef:

                name: fe-api-config

                key: HNG_LESSON_DAY


          - name: HNG_API_ORIGINS
            valueFrom:

              configMapKeyRef:

                name: fe-api-config

                key: HNG_API_ORIGINS



          - name: HNG_API_HOST
            valueFrom:

              configMapKeyRef:

                name: fe-api-config

                key: HNG_API_HOST


          - name: HNG_API_PORT
            valueFrom:

              configMapKeyRef:

                name: fe-api-config

                key: HNG_API_PORT
        ports:

          - containerPort: 8000

        volumeMounts:
        - name: fast-api-data
          mountPath: /api/data

      volumes:
      - name: fast-api-data
        persistentVolumeClaim:
          claimName: fastapi-data-claim

---
apiVersion: v1

kind: Service

metadata:

  name: api-service

spec:

  type: ClusterIP

  selector:

    app: api

  ports:

    - protocol: TCP

      port: 8000

      targetPort: 8000
