version: "3"

networks:
  react-fastapi:
    driver: bridge

volumes:
  fastapi_data:

services:
  frontend:
    depends_on:
      - backend
    container_name: react-frontend
    image: react:day2
    build:
      context: fe
      dockerfile: Dockerfile-day2
    ports:
        - 3000:3000
    env_file:
      - path: ./fe/.env
        required: false
    networks:
      - react-fastapi

  backend:
    container_name: fastapi-backend
    image: fastapi:day2
    build:
      context: api
      dockerfile: Dockerfile-day2
    ports:
        - 8000:8000
    env_file:
      - path: ./api/.env
        required: true
    networks:
      - react-fastapi
    volumes:
      - fastapi_data:/api/data
