apiVersion: v1

kind: Pod

metadata:

  name: mariadbpod

  labels:

    app: fastapi

spec:

  containers:

  - name: fastapi

    image: joseun/fastapi:day1

    ports:

    - containerPort: 8000

    volumeMounts:
    - name: fast-api-data
      mountPath: /api/data

    # env:
    # # Define the environment variable
    # - name: HNG_LESSON_DAY
    #   valueFrom:
    #     configMapKeyRef:
    #       # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
    #       name: react-fastapi-config
    #       # Specify the key associated with the value
    #       key: hng_lesson_day
      
    # - name: HNG_API_ORIGINS
    #   valueFrom:
    #     configMapKeyRef:
    #       # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
    #       name: react-fastapi-config
    #       # Specify the key associated with the value
    #       key: hng_api_origins

    # - name: HNG_API_HOST
    #   valueFrom:
    #     configMapKeyRef:
    #       # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
    #       name: react-fastapi-config
    #       # Specify the key associated with the value
    #       key: hng_api_host
      
    # - name: HNG_API_PORT
    #   valueFrom:
    #     configMapKeyRef:
    #       # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
    #       name: react-fastapi-config
    #       # Specify the key associated with the value
    #       key: hng_api_port
  
  volumes:
  - name: fast-api-data
    persistentVolumeClaim:
      claimName: fastapi-data-claim
