apiVersion: apps/v1

kind: Deployment

metadata:

  name: react-deployment

spec:

  replicas: 1

  selector:

    matchLabels:

      app: react

  template:

    metadata:

      labels:

        app: react

    spec:

      containers:

      - name: react-frontend

        image: joseun/react:day1

        env:
        # Define the environment variable

          - name: REACT_APP_API_URL
            valueFrom:
              configMapKeyRef:
                # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
                name: react-fastapi-config
                # Specify the key associated with the value
                key: react_app_api_url
            
          - name: REACT_APP_LESSON_DAY
            valueFrom:
              configMapKeyRef:
                # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
                name: react-fastapi-config
                # Specify the key associated with the value
                key: react_app_lesson_day

---
apiVersion: v1

kind: Service

metadata:

  name: react-service

spec:

  type: NodePort

  selector:

    app: react

  ports:

    - protocol: TCP

      port: 3000

      targetPort: 3000

      nodePort: 30000
